set -g history-limit 50000
set -g mouse on
set -g default-terminal "tmux-256color"
set -g base-index 1
set -g pane-base-index 1
set -g escape-time 0
set -g repeat-time 600
set -g display-time 2000
set -g status-interval 5
set -g status-style "bg=colour236,fg=colour255"
set -g status-left "#[bg=colour25,fg=white] RAVENA #[default] "
set -g status-left-length 20
set -g status-right "#[fg=colour111]#(uptime | awk -F\"[a-z]*\" '\''{print \"UP:\"\$2}'\'') | #[fg=colour119]#(/usr/local/bin/horas 2>/dev/null | head -1) #[default]"
set -g window-status-current-style "bg=colour31,fg=black"
set -g pane-border-style "fg=colour238"
set -g pane-active-border-style "fg=colour75"
# rolagem
bind PgUp copy-mode -u
bind PgDn copy-mode -d
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "select-pane -t =; copy-mode -e; send-keys -M"
bind -n WheelDownPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "select-pane -t =; send-keys -M"
# janelas
bind c new-window -c "#{pane_current_path}"
bind x kill-pane
bind "|" split-window -h -c "#{pane_current_path}"
bind "-" split-window -v -c "#{pane_current_path}"
